// Citações de filósofos para a página inicial (traduções livres; fonte indicada para conferência).
export const CITACOES = [
  { tipo: 'Incentivo', texto: 'Não é porque as coisas são difíceis que não ousamos; é porque não ousamos que elas são difíceis.', autor: 'Sêneca', fonte: 'Cartas a Lucílio, 104' },
  { tipo: 'Disciplina', texto: 'Enquanto adiamos, a vida passa.', autor: 'Sêneca', fonte: 'Cartas a Lucílio, 1' },
  { tipo: 'Rumo', texto: 'Não há vento favorável para quem não sabe aonde vai.', autor: 'Sêneca', fonte: 'Cartas a Lucílio, 71' },
  { tipo: 'Reflexão', texto: 'A alma se tinge da cor dos seus pensamentos.', autor: 'Marco Aurélio', fonte: 'Meditações, V, 16' },
  { tipo: 'Incentivo', texto: 'O obstáculo à ação faz a ação avançar. O que está no caminho torna-se o caminho.', autor: 'Marco Aurélio', fonte: 'Meditações, V, 20' },
  { tipo: 'Reflexão', texto: 'Muito pouco é necessário para uma vida feliz.', autor: 'Marco Aurélio', fonte: 'Meditações, VII, 67' },
  { tipo: 'Disciplina', texto: 'Primeiro diga a si mesmo o que você quer ser; depois faça o que tem de fazer.', autor: 'Epicteto', fonte: 'Discursos, III, 23' },
  { tipo: 'Estudo', texto: 'As raízes da educação são amargas, mas os seus frutos são doces.', autor: 'Aristóteles', fonte: 'segundo Diógenes Laércio, V, 18' },
  { tipo: 'Reflexão', texto: 'Uma vida sem exame não vale a pena ser vivida.', autor: 'Sócrates', fonte: 'Platão, Apologia, 38a' },
  { tipo: 'Começo', texto: 'O começo é a parte mais importante de qualquer trabalho.', autor: 'Platão', fonte: 'A República, 377a' },
  { tipo: 'Estudo', texto: 'Aprender sem pensar é inútil; pensar sem aprender é perigoso.', autor: 'Confúcio', fonte: 'Analectos, II, 15' },
  { tipo: 'Começo', texto: 'Uma jornada de mil léguas começa com um único passo.', autor: 'Lao-Tsé', fonte: 'Tao Te Ching, 64' },
  { tipo: 'Coragem', texto: 'Ousa saber! Tem a coragem de te servires do teu próprio entendimento.', autor: 'Immanuel Kant', fonte: 'O que é o Esclarecimento?, 1784' },
  { tipo: 'Persistência', texto: 'O que não me mata me fortalece.', autor: 'Friedrich Nietzsche', fonte: 'Crepúsculo dos Ídolos, Máximas, 8' },
  { tipo: 'Persistência', texto: 'Tudo o que é excelente é tão difícil quanto raro.', autor: 'Baruch Espinosa', fonte: 'Ética, parte V' },
  { tipo: 'Reflexão', texto: 'Não estrague o que você tem desejando o que não tem.', autor: 'Epicuro', fonte: 'Sentenças Vaticanas, 35' },
  { tipo: 'Reflexão', texto: 'O coração tem razões que a própria razão desconhece.', autor: 'Blaise Pascal', fonte: 'Pensamentos, 277' },
  { tipo: 'Reflexão', texto: 'A palavra é metade de quem fala e metade de quem a escuta.', autor: 'Michel de Montaigne', fonte: 'Ensaios, III, 13' },
  { tipo: 'Liberdade', texto: 'O homem está condenado a ser livre.', autor: 'Jean-Paul Sartre', fonte: 'O existencialismo é um humanismo' },
  { tipo: 'Mudança', texto: 'Ninguém entra duas vezes no mesmo rio.', autor: 'Heráclito', fonte: 'fragmento, via Platão (Crátilo, 402a)' },
  { tipo: 'Estudo', texto: 'Enquanto ensinamos, aprendemos.', autor: 'Sêneca', fonte: 'Cartas a Lucílio, 7' },
  { tipo: 'Disciplina', texto: 'Não é que tenhamos pouco tempo; é que desperdiçamos muito.', autor: 'Sêneca', fonte: 'Sobre a brevidade da vida, 1' },
  { tipo: 'Ação', texto: 'Não percas mais tempo discutindo como deve ser um homem bom. Sê um.', autor: 'Marco Aurélio', fonte: 'Meditações, X, 16' },
  { tipo: 'Foco', texto: 'Faz cada ato da tua vida como se fosse o último.', autor: 'Marco Aurélio', fonte: 'Meditações, II, 5' },
  { tipo: 'Reflexão', texto: 'Não são as coisas que nos perturbam, mas as opiniões que temos sobre elas.', autor: 'Epicteto', fonte: 'Manual, 5' },
  { tipo: 'Estudo', texto: 'Se queres progredir, aceita parecer tolo e ignorante.', autor: 'Epicteto', fonte: 'Manual, 13' },
  { tipo: 'Estudo', texto: 'Todos os homens, por natureza, desejam saber.', autor: 'Aristóteles', fonte: 'Metafísica, I, 1' },
  { tipo: 'Persistência', texto: 'Uma andorinha só não faz verão, nem um só dia.', autor: 'Aristóteles', fonte: 'Ética a Nicômaco, I, 7' },
  { tipo: 'Humildade', texto: 'Só sei que nada sei.', autor: 'Sócrates', fonte: 'Platão, Apologia, 21d (paráfrase)' },
  { tipo: 'Disciplina', texto: 'A primeira e melhor das vitórias é a vitória sobre si mesmo.', autor: 'Platão', fonte: 'As Leis, 626e' },
  { tipo: 'Estudo', texto: 'Saber o que se sabe e saber o que não se sabe: isso é saber.', autor: 'Confúcio', fonte: 'Analectos, II, 17' },
  { tipo: 'Reflexão', texto: 'Quem conhece os outros é inteligente; quem conhece a si mesmo é iluminado.', autor: 'Lao-Tsé', fonte: 'Tao Te Ching, 33' },
  { tipo: 'Propósito', texto: 'Quem tem um porquê para viver suporta quase qualquer como.', autor: 'Friedrich Nietzsche', fonte: 'Crepúsculo dos Ídolos, Máximas, 12' },
  { tipo: 'Reflexão', texto: 'Age de modo que a máxima da tua ação possa valer como lei universal.', autor: 'Immanuel Kant', fonte: 'Fundamentação da Metafísica dos Costumes, 1785' },
  { tipo: 'Talento', texto: 'O talento acerta um alvo que ninguém mais acerta; o gênio acerta um alvo que ninguém mais vê.', autor: 'Arthur Schopenhauer', fonte: 'O Mundo como Vontade e Representação, II, 31' },
  { tipo: 'Método', texto: 'Dividir cada uma das dificuldades em tantas parcelas quanto possível e necessário para melhor resolvê-las.', autor: 'René Descartes', fonte: 'Discurso do Método, II' },
  { tipo: 'Reflexão', texto: 'Penso, logo existo.', autor: 'René Descartes', fonte: 'Discurso do Método, IV' },
  { tipo: 'Estudo', texto: 'Conhecimento é poder.', autor: 'Francis Bacon', fonte: 'Meditationes Sacrae, 1597' },
  { tipo: 'Ação', texto: 'O ótimo é inimigo do bom.', autor: 'Voltaire', fonte: 'La Bégueule, 1772' },
  { tipo: 'Reflexão', texto: 'A vida só pode ser compreendida olhando para trás, mas só pode ser vivida olhando para a frente.', autor: 'Søren Kierkegaard', fonte: 'Diários, 1843' },
  { tipo: 'Estudo', texto: 'Os limites da minha linguagem significam os limites do meu mundo.', autor: 'Ludwig Wittgenstein', fonte: 'Tractatus, 5.6' },
  { tipo: 'Persistência', texto: 'É preciso imaginar Sísifo feliz.', autor: 'Albert Camus', fonte: 'O Mito de Sísifo' },
];

export function citacaoDoDia(data = new Date()) {
  const dia = Math.floor(Date.UTC(data.getFullYear(), data.getMonth(), data.getDate()) / 864e5);
  return dia % CITACOES.length;
}
